// automatically generated by the FlatBuffers compiler, do not modify

package FlatBufs

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AnnouncementList struct {
	_tab flatbuffers.Table
}

func GetRootAsAnnouncementList(buf []byte, offset flatbuffers.UOffsetT) *AnnouncementList {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AnnouncementList{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *AnnouncementList) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AnnouncementList) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AnnouncementList) AnnName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AnnouncementList) AnnList(obj *Announcement, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *AnnouncementList) AnnListLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func AnnouncementListStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func AnnouncementListAddAnnName(builder *flatbuffers.Builder, AnnName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(AnnName), 0)
}
func AnnouncementListAddAnnList(builder *flatbuffers.Builder, AnnList flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(AnnList), 0)
}
func AnnouncementListStartAnnListVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AnnouncementListEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
